spring.datasource.url=jdbc:tc:postgresql:17:///agrowerk_test
spring.datasource.username=test
spring.datasource.password=test

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

CORS_ORIGINS=http://localhost:3000
CLIENT_ENDPOINT=http://localhost:3000

CLOUDINARY_CLOUD_NAME=test
CLOUDINARY_API_KEY=test
CLOUDINARY_API_SECRET=test
WEATHER_API_KEY=fake_key

spring.jpa.hibernate.ddl-auto=update

security.rsa.private-key=keys/private_key.pem
security.rsa.public-key=keys/public_key.pem

openmeteo.api.base-url=https://api.open-meteo.com/v1/forecast
