#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
#
#spring.data.redis.host=
#spring.data.redis.port=
#spring.data.redis.password=
#
#CORS_ORIGINS=http://localhost:3000
#CLIENT_ENDPOINT=http://localhost:3000
CLOUDINARY_CLOUD_NAME=test
CLOUDINARY_API_KEY=test
CLOUDINARY_API_SECRET=test
WEATHER_API_KEY=fake_key
#
#spring.jpa.hibernate.ddl-auto=update